name: DreamPlus
main: com.thedreamsanctuary.main.java.dreamplus.DreamPlus
version: 1.5.0
authors: [Ajcool1050]
description: Eats, Hugs, and Pipes plus more with DreamPlus.
load: POSTWORLD

commands:
    firewalk:
        description: Walk in fire.
    getmedrunk:
        description: Okay, i'll get your drunk.
    getotherdrunk:
        description: Okay, i'll get them a drunk.
    getmejoe:
        description: Okay, i'll get you joe.
    getotherjoe:
        description: Okay, i'll get them joe.
    dhelm:
        description: Where that funky hat.
    dglow:
        description: Fart out fariy sprinkles.
    dtrail:
        description: The ground breaks beneath your feet.
    
permissions:
    dreamplus.command.getmedrunk:
        default: true
    dreamplus.command.dhelm:
        default: true
    dreamplus.command.dtrail:
        default: true
    dreamplus.command.dglow:
        default: true
    dreamplus.command.getotherdrunk:
        defualt: false
    dreamplus.command.getotherjoe:
        defualt: false
    